package tui

import (
	"strings"
	"testing"
	"time"

	"github.com/agentcarto/core/domain"
)

// A reload rebuilds detailRows under an open turn. If the cursor no longer lands
// on a turn row, the turn view has nothing to render: openCurrentTurn closes it.
// Leaving turnOpen set made detailView and turnFullView call each other until the
// stack overflowed.
func TestReloadOffTurnRowClosesTurnView(t *testing.T) {
	ts := time.Date(2026, 7, 10, 1, 0, 0, 0, time.Local)
	turn := []domain.ConvNode{
		{ID: "u1", Timestamp: ts, Events: []domain.Event{{Kind: domain.EventUser, Text: "go", Prompt: "go"}}},
		{ID: "a1", Parent: "u1", Timestamp: ts, Events: []domain.Event{{Kind: domain.EventAssistant, Text: "done"}}},
	}
	c := domain.NewConversation(turn)
	s := domain.Session{PluginID: "claude", AgentType: "claude", SessionID: "s", CWD: "/proj"}
	m := Model{width: 120, height: 20, detailSession: &s}
	u, _ := m.Update(convMsg{c: &c, reset: true})
	m = u.(Model)
	for i, r := range m.detailRows {
		if r.Kind == "turn" {
			m.detailCursor = i
		}
	}
	m.openCurrentTurn(true)
	if !m.turnOpen {
		t.Fatal("test setup: the turn did not open")
	}

	// Park the cursor off any turn row, as a reload that rebuilds the rows can, then
	// let the reload path (reset=false) run.
	m.detailCursor = -1
	m.openCurrentTurn(false)
	if m.turnOpen {
		t.Fatal("the turn view stayed open with the cursor off a turn row")
	}
	// Rendering must terminate and show the turn list, not recurse.
	if out := m.detailView(); strings.TrimSpace(out) == "" {
		t.Fatal("detailView rendered nothing")
	}

	// Even if some future path sets turnOpen without a turn under the cursor, the
	// render falls back to the turn list. Before the fix this overflowed the stack.
	m.turnOpen = true
	m.detailCursor = -1
	if out := m.detailView(); strings.TrimSpace(out) == "" {
		t.Fatal("detailView rendered nothing with turnOpen and no turn row")
	}
}

// A turn opened in the detail view leads with what it amounted to. Someone who
// opened a turn is deciding how much of it to read, and the summary is the part
// that answers that.
func TestTurnBlocksLeadWithTheSummary(t *testing.T) {
	ts := time.Unix(1, 0)
	c := domain.NewConversation([]domain.ConvNode{
		{ID: "u1", Timestamp: ts, Events: []domain.Event{{Kind: domain.EventUser, Text: "やって", Prompt: "やって"}}},
		{ID: "a1", Parent: "u1", Timestamp: ts, Events: []domain.Event{{Kind: domain.EventAssistant, Text: "できた"}}},
	})
	s := domain.Session{PluginID: "claude", AgentType: "claude", SessionID: "x"}
	m := Model{width: 120, height: 30, detailSession: &s}
	u, _ := m.Update(convMsg{c: &c, reset: true})
	m = u.(Model)
	m.summaries = map[int]string{1: "yキーを追加し、OSC 52 でコピー"}
	m.summaryModel = "claude claude-sonnet-5"

	var ids []string
	for _, r := range m.detailRows {
		if r.Kind == "turn" {
			ids = r.Turn
			break
		}
	}
	if len(ids) == 0 {
		t.Fatal("no turn row")
	}
	blocks := m.turnBlocksOf(ids)
	if len(blocks) == 0 {
		t.Fatal("no blocks")
	}
	first := blocks[0]
	if !strings.Contains(first.Label, "SUMMARY") {
		t.Fatalf("the first block is %q, want the summary", first.Label)
	}
	// Generated text has to say so and name what wrote it: everything else in
	// this view is the session verbatim.
	if !strings.Contains(first.Label, "generated") || !strings.Contains(first.Label, "claude-sonnet-5") {
		t.Errorf("the summary block does not say it is generated by whom: %q", first.Label)
	}
	if !first.Open {
		t.Error("the summary is collapsed; it is the reason the turn was opened")
	}
	if strings.Join(first.Body, "") != "yキーを追加し、OSC 52 でコピー" {
		t.Errorf("body=%q", first.Body)
	}

	// Without a summary the turn renders as it always did.
	m.summaries = nil
	for _, b := range m.turnBlocksOf(ids) {
		if strings.Contains(b.Label, "SUMMARY") {
			t.Error("a turn with no summary carries a summary block")
		}
	}
}

// Summaries are keyed by the number the detail view shows, which a block does
// not carry: a wrong lookup would put one turn's summary on another.
func TestTurnNumberOf(t *testing.T) {
	ts := func(n int64) time.Time { return time.Unix(n, 0) }
	c := domain.NewConversation([]domain.ConvNode{
		{ID: "u1", Timestamp: ts(1), Events: []domain.Event{{Kind: domain.EventUser, Text: "a", Prompt: "a"}}},
		{ID: "a1", Parent: "u1", Timestamp: ts(2), Events: []domain.Event{{Kind: domain.EventAssistant, Text: "x"}}},
		{ID: "u2", Parent: "a1", Timestamp: ts(3), Events: []domain.Event{{Kind: domain.EventUser, Text: "b", Prompt: "b"}}},
		{ID: "a2", Parent: "u2", Timestamp: ts(4), Events: []domain.Event{{Kind: domain.EventAssistant, Text: "y"}}},
	})
	s := domain.Session{PluginID: "claude", AgentType: "claude", SessionID: "x"}
	m := Model{width: 120, height: 30, detailSession: &s}
	u, _ := m.Update(convMsg{c: &c, reset: true})
	m = u.(Model)

	seen := map[int]bool{}
	for _, r := range m.detailRows {
		if r.Kind != "turn" {
			continue
		}
		n := m.turnNumberOf(r.Turn)
		if n != r.TurnIndex+1 {
			t.Errorf("turnNumberOf=%d for the row showing #%d", n, r.TurnIndex+1)
		}
		seen[n] = true
	}
	if len(seen) != 2 {
		t.Errorf("numbered %d turns, want 2", len(seen))
	}
	if got := m.turnNumberOf([]string{"not-on-this-branch"}); got != 0 {
		t.Errorf("turnNumberOf of an unknown turn=%d want 0", got)
	}
	if got := m.turnNumberOf(nil); got != 0 {
		t.Errorf("turnNumberOf(nil)=%d want 0", got)
	}
}
